### ISSUE TITLE
Screenshot not showing up on some browsers

### ISSUE THREAD

**Issue by prithirabha** [XAPHNE/AttendanceSystem#2]
Screenshot is not visible on some browsers like [Librewolf](https://librewolf.net) and [Microsoft Edge](https://www.microsoft.com/en-us/edge)

Left one is Librewolf and on right is Microsoft edge

![image](https://github.com/XAPHNE/AttendanceSystem/assets/127822494/7a546345-3517-471f-b7fe-45b2643c2f9a)

**Comment by XAPHNE** [comment]
Using VPN solves this issue

**Comment by prithirabha** [comment]
> Using VPN solves this issue


I want to perform another test before I close this issue for the screenshot below.

![ScreenshotLoginScreen](https://github.com/XAPHNE/AttendanceSystem/assets/127822494/0e72b5ec-21c2-4c30-87fc-3f47bed03d33)

**Comment by XAPHNE** [comment]
Issue is fixed now, thank you @prithirabha

**Comment by prithirabha** [comment]
https://github.com/XAPHNE/AttendanceSystem/commit/c7db81fcc5c6bdd4e512e6204870727bb0554a54

This really fixes it in master, will append to alpha
